---
- name: Provision managed hosts
  redhat.satellite.host:
    organization: "{{ satellite_org }}"
    name: "{{ item.name }}.{{ satellite_domain }}"
    hostgroup: "{{ item.hostgroup }}"
    location: "{{ item.location }}"
    mac: "{{ item.mac }}"
    ip: "{{ item.ip | default(omit) }}"
    build: "{{ item.build | default(true) }}"
    managed: true
    state: present
  loop: "{{ satellite_hosts }}"
  loop_control:
    label: "{{ item.name }}"
