---
- name: Configure Red Hat Satellite
  hosts: satellite
  gather_facts: false

  module_defaults:
    group/redhat.satellite.satellite:
      server_url: "{{ satellite_server_url }}"
      username: "{{ satellite_username }}"
      password: "{{ satellite_password }}"
      validate_certs: "{{ satellite_validate_certs }}"

  roles:
    - satellite_config
